spring:
  datasource:
    url: jdbc:postgresql://postgres-master:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
